# -*- coding: utf-8 -*-
"""hangmanpics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycRroT9BEX4cIKKn16meCVBp6A5o1Qm5
"""

hangmanpics = [r'''
  +---+
  |   |
      |
      |
      |
      |
=========''', r'''
  +---+
  |   |
  O   |
      |
      |
      |
=========''', r'''
  +---+
  |   |
  O   |
  |   |
      |
      |
=========''', r'''
  +---+
  |   |
  O   |
 /|   |
      |
      |
=========''', r'''
  +---+
  |   |
  O   |
 /|\  |
      |
      |
=========''', r'''
  +---+
  |   |
  O   |
 /|\  |
 /    |
      |
=========''', r'''
  +---+
  |   |
  O   |
 /|\  |
 / \  |
      |
=========''']